// apps/owner-center/src/components/ui/ReportLayout.tsx
// Professional report shell — print/export friendly, ACC branding inherited from shell.

import React from 'react';
import { cn } from './types';

export interface ReportMetadataItem {
  label: string;
  value: string;
}

export interface ReportLayoutProps {
  title: string;
  subtitle?: string;
  reference?: string;
  generatedAt?: string;
  generatedBy?: string;
  metadata?: ReportMetadataItem[];
  filterSummary?: string;
  children: React.ReactNode;
  footer?: React.ReactNode;
  className?: string;
}

export function ReportLayout({
  title,
  subtitle,
  reference,
  generatedAt,
  generatedBy,
  metadata,
  filterSummary,
  children,
  footer,
  className,
}: ReportLayoutProps): React.ReactElement {
  return (
    <article className={cn('acc-report', className)}>
      <header className="acc-report__header">
        <div className="acc-report__title-block">
          <h1 className="acc-report__title">{title}</h1>
          {subtitle && <p className="acc-report__subtitle">{subtitle}</p>}
        </div>
        <div className="acc-report__meta-grid">
          {reference && (
            <div className="acc-report__meta-item">
              <span className="acc-report__meta-label">Reference</span>
              <span className="acc-report__meta-value">{reference}</span>
            </div>
          )}
          {generatedAt && (
            <div className="acc-report__meta-item">
              <span className="acc-report__meta-label">Generated</span>
              <span className="acc-report__meta-value">{generatedAt}</span>
            </div>
          )}
          {generatedBy && (
            <div className="acc-report__meta-item">
              <span className="acc-report__meta-label">Generated by</span>
              <span className="acc-report__meta-value">{generatedBy}</span>
            </div>
          )}
          {metadata?.map((item) => (
            <div key={item.label} className="acc-report__meta-item">
              <span className="acc-report__meta-label">{item.label}</span>
              <span className="acc-report__meta-value">{item.value}</span>
            </div>
          ))}
        </div>
        {filterSummary && (
          <p className="acc-report__filters">
            <span className="acc-report__meta-label">Filters: </span>
            {filterSummary}
          </p>
        )}
      </header>

      <div className="acc-report__sections">{children}</div>

      <footer className="acc-report__footer">
        {footer ?? (
          <p className="acc-report__footer-text">
            ACC Reliability Platform — Confidential Engineering Report
          </p>
        )}
      </footer>
    </article>
  );
}

export interface ReportSectionProps {
  title: string;
  children: React.ReactNode;
  className?: string;
}

export function ReportSection({ title, children, className }: ReportSectionProps): React.ReactElement {
  return (
    <section className={cn('acc-report__section', className)}>
      <h2 className="acc-report__section-title">{title}</h2>
      <div className="acc-report__section-body">{children}</div>
    </section>
  );
}
