/**
 * Canonical error codes for Apps Script API responses.
 * @see response.gs
 */
var ErrorCodes = {
  MISSING_ACTION: 'MISSING_ACTION',
  UNKNOWN_ACTION: 'UNKNOWN_ACTION',
  INVALID_JSON: 'INVALID_JSON',
  MISSING_BODY: 'MISSING_BODY',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  MISSING_SPREADSHEET_ID: 'MISSING_SPREADSHEET_ID',
  SHEET_NOT_FOUND: 'SHEET_NOT_FOUND',
  MISSING_REQUIRED_ID: 'MISSING_REQUIRED_ID',
  RECORD_NOT_FOUND: 'RECORD_NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
};
