// modules/oil-lubrication/src/types.ts
// Domain types for the Oil Lubrication module.
//
// All types are pure data contracts — no methods, no classes.
// Repository and service interfaces depend on these types only.
//
// Key identifiers:
//   EquipmentId        — master platform equipment key (Equipment_ID)
//   LubricationPointId — physical lubrication point on a piece of equipment (LP_ID)
//   OilChangeRecordId  — unique identifier for a single oil change record
//
// Sprint 03 additions:
//   AttachmentReference — photo/document URI value object
//   LpStatusBucket      — computed status classification for lubrication points
//   LubricationPoint    — extended with standardQuantityL, areaName, pointCode, position
//   OilChangeRecord     — extended with filterChanged, breatherServiced, runningHours,
//                         technicianName, attachmentReference

import type { IsoTimestamp } from '@acc-reliability/shared-types';
import type {
  ContractorId,
  UserId,
  Entity,
  QueryOptions,
  PagedQueryOptions,
  PageResult,
  EquipmentId,
} from '@acc-reliability/sdk';

// ── Branded identifiers ───────────────────────────────────────────────────────

/** Unique identifier for a single oil change record. */
export type OilChangeRecordId = string & { readonly __brand: 'OilChangeRecordId' };

/**
 * Lubrication Point identifier (LP_ID).
 *
 * Identifies a specific physical lubrication point on a piece of equipment.
 * A single equipment unit may have multiple lubrication points.
 */
export type LubricationPointId = string & { readonly __brand: 'LubricationPointId' };

/**
 * Creates an {@link OilChangeRecordId} from a raw string.
 * @throws {Error} if value is empty after trimming.
 */
export function createOilChangeRecordId(value: string): OilChangeRecordId {
  const trimmed = value.trim();
  if (trimmed.length === 0) throw new Error('OilChangeRecordId cannot be empty');
  return trimmed as OilChangeRecordId;
}

/**
 * Creates a {@link LubricationPointId} from a raw string.
 * @throws {Error} if value is empty after trimming.
 */
export function createLubricationPointId(value: string): LubricationPointId {
  const trimmed = value.trim();
  if (trimmed.length === 0) throw new Error('LubricationPointId cannot be empty');
  return trimmed as LubricationPointId;
}

// ── Oil change status ─────────────────────────────────────────────────────────

/**
 * Lifecycle status of an oil change record.
 *
 * - `scheduled`   — due but not yet performed
 * - `in-progress` — work order open, not yet completed
 * - `completed`   — oil change performed and recorded
 * - `overdue`     — past scheduled date without completion
 * - `cancelled`   — voided; no oil change was performed; history preserved
 */
export type OilChangeStatus =
  | 'scheduled'
  | 'in-progress'
  | 'completed'
  | 'overdue'
  | 'cancelled';

// ── Oil change source ─────────────────────────────────────────────────────────

/**
 * What triggered the oil change event.
 *
 * - `manual`                  — technician-initiated without a formal work order
 * - `work-order`              — originated from a maintenance work order
 * - `preventive-maintenance`  — generated by a scheduled PM programme
 * - `inspection`              — identified and recorded during an equipment inspection
 */
export type OilChangeSource =
  | 'manual'
  | 'work-order'
  | 'preventive-maintenance'
  | 'inspection';

// ── Oil change frequency ──────────────────────────────────────────────────────

/**
 * Scheduling interval for recurring oil changes on a lubrication point.
 *
 * At least one of {@link intervalDays} or {@link intervalOperatingHours} must
 * be provided. When both are set the sooner threshold governs.
 */
export interface OilChangeFrequency {
  /** Calendar interval in whole days (e.g. 90 = quarterly). */
  readonly intervalDays?: number | undefined;
  /** Operating-hours interval (e.g. 500 = every 500 h of equipment runtime). */
  readonly intervalOperatingHours?: number | undefined;
  /** Free-text scheduling notes visible to technicians. */
  readonly notes?: string | undefined;
}

// ── LP status bucket ──────────────────────────────────────────────────────────

/**
 * Computed status classification for a lubrication point.
 *
 * This is a derived value — never stored on the entity. Computed by
 * {@link SchedulingService.computeStatusBucket} from the LP's next due date
 * (derived from the latest approved oil change record) and active flag.
 *
 * Buckets (in priority order):
 * - `inactive`    — point is deactivated; no scheduling applies
 * - `no-history`  — point is active but has never been serviced
 * - `overdue`     — past the computed next due date
 * - `due-today`   — next due date is today
 * - `due-soon`    — next due date is within 7 calendar days
 * - `ok`          — next due date is more than 7 days away
 */
export type LpStatusBucket =
  | 'overdue'
  | 'due-today'
  | 'due-soon'
  | 'ok'
  | 'no-history'
  | 'inactive';

// ── Attachment reference value object ─────────────────────────────────────────

/**
 * A reference to an externally stored file (photo, document, PDF).
 *
 * The platform does not own file storage in RC1. Attachments are referenced
 * by URI only (e.g. a Google Drive share link pasted by the technician).
 * No upload is implemented; this value object stores the reference metadata.
 */
export interface AttachmentReference {
  /** URI pointing to the external file (e.g. Google Drive share link). */
  readonly uri: string;
  /** ISO 8601 UTC timestamp when the reference was recorded. */
  readonly uploadedAt: IsoTimestamp;
  /** Optional human-readable label (e.g. "Completion photo", "Lab PDF"). */
  readonly label?: string | undefined;
}

// ── Lubrication Point entity ──────────────────────────────────────────────────

/**
 * A named physical location on a piece of equipment where lubrication
 * is applied (LP_ID record).
 *
 * Each LubricationPoint belongs to exactly one equipment unit and one
 * contractor. Deactivating a point (isActive = false) retains history.
 *
 * Computed fields NOT stored on this entity:
 *   - lastChangeDate  → derived from latest completed OilChangeRecord.performedAt
 *   - nextDueDate     → derived by SchedulingService from lastChangeDate + frequency
 *   - statusBucket    → derived by SchedulingService from nextDueDate + isActive
 */
export interface LubricationPoint extends Entity {
  /** Platform-assigned unique identifier. */
  readonly id: string;
  /** Lubrication Point key (LP_ID). */
  readonly lubricationPointId: LubricationPointId;
  /** Equipment unit this point belongs to (Equipment_ID). */
  readonly equipmentId: EquipmentId;
  /** Contractor that owns this lubrication point record. */
  readonly contractorId: ContractorId;
  /** Human-readable name (e.g. "Main Bearing", "Gearbox Input Shaft"). */
  readonly name: string;
  /** Physical location description on the equipment (e.g. "Top left, facing motor"). */
  readonly location?: string | undefined;
  /** Lubricant specification required at this point (e.g. "ISO VG 46"). */
  readonly lubricantSpec?: string | undefined;
  /** Recommended oil change frequency for this lubrication point. */
  readonly frequency?: OilChangeFrequency | undefined;
  /** Whether this lubrication point is currently active. Deactivated points are retained for history. */
  readonly isActive: boolean;
  /** ISO 8601 UTC timestamp when this record was created in the platform. */
  readonly createdAt: IsoTimestamp;
  /** ISO 8601 UTC timestamp when this record was last modified. */
  readonly updatedAt: IsoTimestamp;

  // ── Sprint 03 fields ────────────────────────────────────────────────────────

  /**
   * Expected oil volume in litres for a standard change at this point.
   * Used by SchedulingService to detect quantity deviation alerts.
   */
  readonly standardQuantityL?: number | undefined;
  /**
   * Plant area or zone where this lubrication point is located
   * (e.g. "Area-01", "Compressor Hall").
   * Distinct from `location` which describes the physical position on the equipment.
   */
  readonly areaName?: string | undefined;
  /**
   * Internal short code for this lubrication point (e.g. "LP-011").
   * Distinct from the stable `lubricationPointId` business key.
   */
  readonly pointCode?: string | undefined;
  /**
   * Physical position on the equipment (e.g. "Drive End", "Top mounting face").
   * More specific than `location`; used on oil change forms and route items.
   */
  readonly position?: string | undefined;
}

// ── Lubrication Point create / update requests ────────────────────────────────

/** Input payload for registering a new lubrication point. */
export interface LubricationPointCreateRequest {
  readonly lubricationPointId: LubricationPointId;
  readonly equipmentId: EquipmentId;
  readonly contractorId: ContractorId;
  readonly name: string;
  readonly location?: string | undefined;
  readonly lubricantSpec?: string | undefined;
  readonly frequency?: OilChangeFrequency | undefined;
  readonly standardQuantityL?: number | undefined;
  readonly areaName?: string | undefined;
  readonly pointCode?: string | undefined;
  readonly position?: string | undefined;
}

/**
 * Partial update payload for an existing lubrication point.
 * Identity fields (id, lubricationPointId, equipmentId, contractorId) cannot be updated.
 */
export interface LubricationPointUpdateRequest {
  readonly name?: string | undefined;
  readonly location?: string | undefined;
  readonly lubricantSpec?: string | undefined;
  readonly frequency?: OilChangeFrequency | undefined;
  readonly standardQuantityL?: number | undefined;
  readonly areaName?: string | undefined;
  readonly pointCode?: string | undefined;
  readonly position?: string | undefined;
}

// ── Oil Change Record entity ──────────────────────────────────────────────────

/**
 * Represents a single oil change event performed on a piece of equipment.
 *
 * Contractor isolation is enforced at the repository layer; every query is
 * scoped to the {@link contractorId} embedded in the repository instance.
 * This entity always belongs to exactly one contractor.
 *
 * Hard deletion is prohibited. Use {@link OilLubricationService.cancelRecord}
 * to void a record; the `cancelled` status preserves the audit trail.
 */
export interface OilChangeRecord extends Entity {
  /** Platform-assigned unique identifier. */
  readonly id: string;
  /** Equipment on which the oil change was performed (master Equipment_ID). */
  readonly equipmentId: EquipmentId;
  /** Contractor that owns this record. */
  readonly contractorId: ContractorId;
  /**
   * Lubrication Point identifier (LP_ID).
   * Present when the equipment has named lubrication points.
   */
  readonly lubricationPointId?: LubricationPointId | undefined;
  /** Lifecycle status of this oil change record. */
  readonly status: OilChangeStatus;
  /** What triggered this oil change. */
  readonly source: OilChangeSource;
  /** Oil type or grade applied (e.g. "ISO VG 46", "Shell Omala S2 G 220"). */
  readonly oilType: string;
  /** Volume of oil applied, in litres. */
  readonly quantityLitres: number;
  /** ISO 8601 UTC timestamp when the oil change was performed in the field. */
  readonly performedAt: IsoTimestamp;
  /** Platform user who recorded the completion. */
  readonly completedBy: UserId;
  /** Optional maintenance work order reference. */
  readonly workOrderId?: string | undefined;
  /** Optional technician notes. */
  readonly notes?: string | undefined;
  /** ISO 8601 UTC timestamp when this record was created in the platform. */
  readonly createdAt: IsoTimestamp;
  /** ISO 8601 UTC timestamp when this record was last modified. */
  readonly updatedAt: IsoTimestamp;

  // ── Sprint 03 fields ────────────────────────────────────────────────────────

  /** Whether the oil filter was replaced during this service. */
  readonly filterChanged?: boolean | undefined;
  /** Whether the breather/vent was serviced during this oil change. */
  readonly breatherServiced?: boolean | undefined;
  /**
   * Equipment running hours recorded at the time of service.
   * Used by SchedulingService for operating-hours-based scheduling.
   */
  readonly runningHours?: number | undefined;
  /**
   * Name of the technician who physically performed the service.
   * May differ from `completedBy` when a supervisor records on behalf of a technician.
   */
  readonly technicianName?: string | undefined;
  /**
   * Optional reference to a photo or document (e.g. completion photo, lab PDF).
   * The URI is pasted by the user; no file upload is implemented in Sprint 03.
   */
  readonly attachmentReference?: AttachmentReference | undefined;
}

// ── Create request ────────────────────────────────────────────────────────────

/**
 * Input payload for recording a new oil change event.
 *
 * `status` defaults to `'completed'` and `source` defaults to `'manual'`
 * when omitted; the service applies these defaults before persisting.
 */
export interface OilChangeRecordCreateRequest {
  readonly equipmentId: EquipmentId;
  readonly contractorId: ContractorId;
  readonly lubricationPointId?: LubricationPointId | undefined;
  /** @default 'completed' */
  readonly status?: OilChangeStatus | undefined;
  /** @default 'manual' */
  readonly source?: OilChangeSource | undefined;
  readonly oilType: string;
  readonly quantityLitres: number;
  readonly performedAt: IsoTimestamp;
  readonly completedBy: UserId;
  readonly workOrderId?: string | undefined;
  readonly notes?: string | undefined;
  readonly filterChanged?: boolean | undefined;
  readonly breatherServiced?: boolean | undefined;
  readonly runningHours?: number | undefined;
  readonly technicianName?: string | undefined;
  readonly attachmentReference?: AttachmentReference | undefined;
}

// ── Update request ────────────────────────────────────────────────────────────

/**
 * Partial update payload for an existing oil change record.
 * Only fields present in this object are modified; absent fields are unchanged.
 * Identity fields (id, equipmentId, contractorId, completedBy) cannot be updated.
 */
export interface OilChangeRecordUpdateRequest {
  readonly status?: OilChangeStatus | undefined;
  readonly source?: OilChangeSource | undefined;
  readonly oilType?: string | undefined;
  readonly quantityLitres?: number | undefined;
  readonly performedAt?: IsoTimestamp | undefined;
  readonly workOrderId?: string | undefined;
  readonly notes?: string | undefined;
  readonly filterChanged?: boolean | undefined;
  readonly breatherServiced?: boolean | undefined;
  readonly runningHours?: number | undefined;
  readonly technicianName?: string | undefined;
  readonly attachmentReference?: AttachmentReference | undefined;
}

// ── Summary projection ────────────────────────────────────────────────────────

/** Lightweight read model for rendering oil change record lists. */
export interface OilChangeRecordSummary {
  readonly id: string;
  readonly equipmentId: EquipmentId;
  readonly lubricationPointId?: LubricationPointId | undefined;
  readonly status: OilChangeStatus;
  readonly source: OilChangeSource;
  readonly oilType: string;
  readonly quantityLitres: number;
  readonly performedAt: IsoTimestamp;
  readonly completedBy: UserId;
}

// ── Repository contracts ──────────────────────────────────────────────────────

/**
 * Domain repository for oil change records.
 *
 * Instances are contractor-scoped; contractor isolation is enforced by the
 * storage layer at repository creation time via {@link IStorageClient.getRepository}.
 * Individual method calls do not require a {@link ContractorId} parameter.
 */
export interface IOilChangeRecordRepository {
  findById(id: string): Promise<OilChangeRecord | null>;
  findByEquipmentId(
    equipmentId: EquipmentId,
    options?: QueryOptions<OilChangeRecord>
  ): Promise<readonly OilChangeRecord[]>;
  findPaged(options: PagedQueryOptions<OilChangeRecord>): Promise<PageResult<OilChangeRecord>>;
  create(data: Omit<OilChangeRecord, 'id'>): Promise<OilChangeRecord>;
  update(id: string, changes: OilChangeRecordUpdateRequest): Promise<OilChangeRecord>;
  delete(id: string): Promise<void>;
}

/**
 * Domain repository for lubrication points (LP_ID records).
 *
 * Instances are contractor-scoped. Lubrication points are never hard-deleted;
 * use {@link deactivate} to retire a point while preserving history.
 */
export interface ILubricationPointRepository {
  findById(id: string): Promise<LubricationPoint | null>;
  findByLubricationPointId(lpId: LubricationPointId): Promise<LubricationPoint | null>;
  findByEquipmentId(
    equipmentId: EquipmentId,
    options?: QueryOptions<LubricationPoint>
  ): Promise<readonly LubricationPoint[]>;
  findPaged(options: PagedQueryOptions<LubricationPoint>): Promise<PageResult<LubricationPoint>>;
  create(data: Omit<LubricationPoint, 'id'>): Promise<LubricationPoint>;
  update(id: string, changes: LubricationPointUpdateRequest): Promise<LubricationPoint>;
  /** Soft-delete: sets isActive to false. Hard delete is not permitted. */
  deactivate(id: string): Promise<LubricationPoint>;
}
